### PR TITLE
ENH: Update extension metadata

### PR DESCRIPTION
**Pull request by jcfr**
Consolidate extension metadata based on the corresponding s4ext file organized
in the ExtensionsIndex repository.

### CODE REVIEW

**Comment by jcfr** [comment]
@ikolesov @ljzhu It would be great if this could be reviewed and integrated :pray: 

cc: @lassoan @pieper

**Comment by jcfr** [comment]
Please, could this be reviewed & merged :pray:

**Comment by jcfr** [comment]
Email sent on June 13th 2024 to @ljzhu, @ikolesov, @pkarasev3 and "Allen Tannenbaum" with @lassoan and @pieper in cc:

```
Subject: Help to merge https://github.com/ikolesov/CarreraSlice/pull/13

Hi Ivan, Liangjia, Peter and Allen,

When you have a chance, we would appreciate your help to merge the following pull request:

  ENH: Update extension metadata
  https://github.com/ikolesov/CarreraSlice/pull/13

Changes are trivial as they only include updates to the extension metadata.

Alternatively, you could look into archiving the extension. This would be done by updating its README, its project description, and then archiving it following these instructions (https://docs.github.com/en/repositories/archiving-a-github-repository/archiving-repositories#archiving-a-repository).

For examples, see these projects:
* https://github.com/Slicer/SlicerTranslations
* https://github.com/SCIInstitute/Cleaver1

Once this is done, let us know and we will update https://github.com/Slicer/ExtensionsIndex/blob/main/ARCHIVE/README.md

Thanks
J-Christophe
```

**Comment by jcfr** [comment]
Follow-up email sent on June 19th 2024 to @ljzhu, @ikolesov, @pkarasev3 and "Allen Tannenbaum" with @lassoan and @pieper in cc:

```
Hi Ivan, Liangjia, Peter and Allen,

Let us know if you need anything to move forward with the integration of the referenced pull requests.

Thanks
J-Christophe
```

**Comment by ljzhu** [comment]
Thanks a lot, Superman! We are on traveling and will be back next week.

Have a wonderful summer!

Liangjia

**Comment by jcfr** [comment]
@ikolesov @ljzhu  Thanks for taking the time to follow-up :pray: :rocket:

**Pull request merged**
