### PR TITLE
Improve build system and add qt5 + VTK8 support

### PR DESCRIPTION
**Pull request by jcfr**

### CODE REVIEW

**Comment by jcfr** [comment]
@ikolesov @ljzhu  Would be great if you could integrate this PR. It simplifies the overall extension. and allowed us to detect few issues with the Slicer+VTK8 build system.

If you end up working on the code, I suggest to look into using the Segmentation editor effect developed by @lassoan

**Comment by ljzhu** [comment]
@jcfr Hi JC, I just merged the commits. Please let me know if it works. Thanks.

**Comment by jcfr** [comment]
Thanks.

Few comments:

* [ ] Consider updating the corresponding [description file](https://github.com/Slicer/ExtensionsIndex/blob/master/CarreraSlice.s4ext).

* [ ] Then, as described [here](https://www.slicer.org/wiki/Documentation/Nightly/Developers/Tutorials/BuildTestPackageDistributeExtensions#Continuous_Integration), later tomorrow and anytime afterward you could this link to check the status of your extension:

http://slicer.cdash.org/index.php?project=Slicer4&filtercount=1&showfilters=1&field1=buildname&compare1=63&value1=CarreraSlice

**Comment by jcfr** [comment]
@ljzhu I improved the Slicer extension wizard to support `CMakeLists.txt` in subdirectory. See https://github.com/Slicer/Slicer/pull/814

With this improvement, I was able to easily create a PR updating the CarreraSlice description file:
https://github.com/Slicer/ExtensionsIndex/pull/1473

The steps were:

```
$ git clone git@github.com:ikolesov/CarreraSlice.git
$ /path/to/Slicer-build/Slicer-build/bin/slicerExtensionWizard --contribute .
```
See https://www.slicer.org/wiki/Documentation/Nightly/Developers/Tutorials/Contribute_Extension_Description_File_using_Extension_Wizard

**Pull request merged**
